name       : kdegraphics-mobipocket
version    : 18.08.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kdegraphics-mobipocket-18.08.0.tar.xz : eab8e791606580e5ee369ab27b459f46e7d0a6589e3ca2efb27861114c646b5c
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
