name       : kdegraphics-mobipocket
version    : 22.08.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/kdegraphics-mobipocket-22.08.3.tar.xz : 9c70467d7b574dc8c61dd88f4714e50606f5a9c6da5e83016c5bde451cec58ca
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
