name       : kdegraphics-mobipocket
version    : 20.04.3
release    : 39
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/kdegraphics-mobipocket-20.04.3.tar.xz : 24ce0c1565b8bc922ea08c3d6bb625ff4bba2e656545e09e410a0ff3bc84c80f
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
