name       : kdegraphics-mobipocket
version    : 20.12.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kdegraphics-mobipocket-20.12.3.tar.xz : 9448b979b9722bc73bd0429733016399933f9c41f19b5cc1ecb8458226fd71fd
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
