name       : kdegraphics-mobipocket
version    : 18.08.1
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kdegraphics-mobipocket-18.08.1.tar.xz : f69fa0dd72b584533dc0bc60625b44a154d3b40d118afcda3724313eec135c8e
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
