name       : kdegraphics-mobipocket
version    : 19.08.3
release    : 30
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/kdegraphics-mobipocket-19.08.3.tar.xz : d9ea38255c967dcf0de820e6ad663e721188f5541c18c459e611f6d72ddc8e8f
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
