name       : kdegraphics-mobipocket
version    : 20.12.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/kdegraphics-mobipocket-20.12.1.tar.xz : 0d06f12fa1a5475d703839f2974806acb54b7c8ce0a5068e75144c561c237dd8
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
