name       : kdegraphics-mobipocket
version    : 19.04.3
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kdegraphics-mobipocket-19.04.3.tar.xz : c073730b7f3d468f4e710a67bdb90d794b69bf0f2c149f7fac705b44b912fa94
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
