name       : kdegraphics-mobipocket
version    : 19.12.1
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kdegraphics-mobipocket-19.12.1.tar.xz : 546d11af89e97831cc09868051142d4180e9621cc537c2941272b42a85e71c6a
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
