name       : kdegraphics-mobipocket
version    : 18.08.2
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kdegraphics-mobipocket-18.08.2.tar.xz : dca306ae117e5f7146b5d2b9f57232229052ef8c36f6ff45bffdd1bd4cb44bc7
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
