name       : kdegraphics-mobipocket
version    : 18.12.3
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.3/src/kdegraphics-mobipocket-18.12.3.tar.xz : 69ae8b6f45b8c9ec3a73e636f7a779257ebbd6f8016d24294bec844a51f2cc52
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
