name       : kdegraphics-mobipocket
version    : 17.08.2
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kdegraphics-mobipocket-17.08.2.tar.xz : 6f635c86cd6dd8869f7491a3cfa4533bbc68c50f55ae20792a07885351b81801
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
