name       : kdegraphics-mobipocket
version    : 20.04.1
release    : 37
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kdegraphics-mobipocket-20.04.1.tar.xz : 1a617212f196be24a23620a238c7918d00fa2f56280ee5a6f139797d7628e2b2
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
