name       : kdegraphics-mobipocket
version    : 16.12.3
release    : 2
source     :
    - http://download.kde.org/stable/applications/16.12.3/src/kdegraphics-mobipocket-16.12.3.tar.xz : 829362ad385784ad389d05fa73ddd538f8731b5ff9c6030bd287ab1691b7f81b
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
