name       : kdegraphics-mobipocket
version    : 18.04.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kdegraphics-mobipocket-18.04.0.tar.xz : 16baaf08af6a2415cbcf1e68c7547d1bf0d4be0a6d79a8a9862a6becc704e005
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
