name       : kdegraphics-mobipocket
version    : 17.12.1
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kdegraphics-mobipocket-17.12.1.tar.xz : 86e5231fae4ee80e870bec772f72a32efd794bbf3d7b56fe9eff88fc25067025
license    : GPL-2.0
component  : programming
optimize   : lto
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
