name       : kdegraphics-mobipocket
version    : 19.08.2
release    : 29
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/kdegraphics-mobipocket-19.08.2.tar.xz : 9621b0b3564ce7fcd6890c15c48e11d00c1cf2d3b408b255ec590bd6d113439f
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
