name       : kdegraphics-mobipocket
version    : 21.08.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kdegraphics-mobipocket-21.08.3.tar.xz : 152e111b312e3b75a971f43430ee41e7df46cff4734ba9e5bdaffa2a1a0591ae
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
