name       : kdegraphics-mobipocket
version    : 17.04.0
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kdegraphics-mobipocket-17.04.0.tar.xz : 03795ec8d2709c00123a87097132ae63bcc2b649953b278dff804f76ae514749
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
