name       : kdegraphics-mobipocket
version    : 19.08.0
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.0/src/kdegraphics-mobipocket-19.08.0.tar.xz : 28c6566f32855a43d10829070cc47d0f4c879ca89eb3228ea6274d0f32fa90fe
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
