name       : kdegraphics-mobipocket
version    : 20.12.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kdegraphics-mobipocket-20.12.2.tar.xz : c6844a0b7a84cac2f6d3b1a44645488b3dd5fc8e89214a0c512a7eb7ef8e4409
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
