name       : kdegraphics-mobipocket
version    : 19.12.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/kdegraphics-mobipocket-19.12.0.tar.xz : c0f59133d66084b3341e02cfe91341cfb5722166b24a43e6e7b4f8a11badbf82
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
