name       : kdegraphics-mobipocket
version    : 23.04.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kdegraphics-mobipocket-23.04.0.tar.xz : 257839a383614098fc60031d689145bf1d99844c835aacbc08bf34d21542b0c2
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
