name       : kdegraphics-mobipocket
version    : 22.04.3
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/kdegraphics-mobipocket-22.04.3.tar.xz : 521fae7172263f888ddb98f15c69d9b417a9d477e66c0782d31d132684e2d98b
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
