name       : kdegraphics-mobipocket
version    : 19.04.0
release    : 23
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.0/src/kdegraphics-mobipocket-19.04.0.tar.xz : 37db302ed0d70766cf75e052f27150553b875428b68c886fe4d16452edd18939
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
