name       : kdegraphics-mobipocket
version    : 19.12.2
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kdegraphics-mobipocket-19.12.2.tar.xz : 3227c6157216cafe793aa66e29a4f095e673ba4f8de532dc95cd94d11b6cdf10
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
