name       : kdegraphics-mobipocket
version    : 21.08.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/kdegraphics-mobipocket-21.08.2.tar.xz : 97d1bec263559992d28e97d03907974af6a6a1af5e5050810a767cc79d3e8d97
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
