name       : kdegraphics-mobipocket
version    : 21.04.3
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kdegraphics-mobipocket-21.04.3.tar.xz : 74b51326f7eeaa4f0e306575b67ae3dfc6215ac711cad31861e68b6fc8d94725
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
