name       : kdegraphics-mobipocket
version    : 20.12.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/kdegraphics-mobipocket-20.12.0.tar.xz : 6572bd16eb1af1a1fe458ea898e8391a74a37997047a39f3fbc0bc742940a83a
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
