name       : kdegraphics-mobipocket
version    : 23.04.2
release    : 68
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/kdegraphics-mobipocket-23.04.2.tar.xz : 1d99f29a1bfb16cc1b0ff043a95cc98bea42f43a2ed0c53d8e16baf9f440d802
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
