name       : kdegraphics-mobipocket
version    : 21.12.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/kdegraphics-mobipocket-21.12.3.tar.xz : 58c4dc769972a1472a9cfe1d134a77a12e9a78357829247d247aa73bc8e83124
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
