name       : kdegraphics-mobipocket
version    : 18.04.3
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/kdegraphics-mobipocket-18.04.3.tar.xz : 71a3ea1432a162724f59331d5682baac91c0a2413143adf4efb31ff58add8819
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
