name       : kdegraphics-mobipocket
version    : 18.08.3
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.3/src/kdegraphics-mobipocket-18.08.3.tar.xz : 624a20578aa9d079c23ff2968ff529274044b06b4d276e253994d6c73e8b6b62
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
