name       : kdegraphics-mobipocket
version    : 22.04.1
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kdegraphics-mobipocket-22.04.1.tar.xz : e7e31efa63d478b049aca107bf8fd9731fcc357b67fdc62dab3f3307f4d41f5d
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
