name       : kdegraphics-mobipocket
version    : 23.04.1
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.1/src/kdegraphics-mobipocket-23.04.1.tar.xz : 48dda7bfb67c46397eedb8966373199a34ccbb61a8b8369c7b2301b822cc6941
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
