name       : kdegraphics-mobipocket
version    : 19.08.1
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kdegraphics-mobipocket-19.08.1.tar.xz : b1760e3a22869715881f571c0bc79c1b91876e41f508a5ba53659be774a6628c
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
