name       : kdegraphics-mobipocket
version    : 23.04.3
release    : 69
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.3/src/kdegraphics-mobipocket-23.04.3.tar.xz : bb65bd302a97466ed08c34668d32f61e50cfeadade73f3365d7a93566033168e
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
