name       : kdegraphics-mobipocket
version    : 20.08.3
release    : 43
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.3/src/kdegraphics-mobipocket-20.08.3.tar.xz : 1876ef0993214c97ddd31105a230c7f68835c050279898893fb9d77b2c5fdd45
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
