name       : kdegraphics-mobipocket
version    : 18.12.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kdegraphics-mobipocket-18.12.0.tar.xz : 51eaffea48cd637dca26a8b9ac31cc8164a2954004dccd58353a5c42f3b2fd15
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
