name       : kdegraphics-mobipocket
version    : 17.08.3
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kdegraphics-mobipocket-17.08.3.tar.xz : d231144a3f3fcbd525933645732a82c173a20dfcca09e024607616012921d1e5
license    : GPL-2.0
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
