name       : kdegraphics-mobipocket
version    : 21.04.2
release    : 51
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.2/src/kdegraphics-mobipocket-21.04.2.tar.xz : f7ad0ed2eb7c8d0547bb24279bdac564d352ac2d639c58c057dda5e2bcf64364
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
