name       : kdegraphics-mobipocket
version    : 20.08.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/kdegraphics-mobipocket-20.08.0.tar.xz : 2c11b6efe2c5f7725341c861dd9ba8e919ba3734866e808225c13bb2f2d90a2d
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
