name       : kdegraphics-mobipocket
version    : 20.04.2
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.2/src/kdegraphics-mobipocket-20.04.2.tar.xz : 3627ff68b46cabbb45b62fb7feb18a55b4295844979fc16f1552ac0eba097b56
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
