name       : kdegraphics-mobipocket
version    : 18.12.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.2/src/kdegraphics-mobipocket-18.12.2.tar.xz : 58233f44db9ab0b7f6233aced377d55f5101459b92a7e153a8ca055e75fe0c41
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
