name       : kdegraphics-mobipocket
version    : 20.08.1
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kdegraphics-mobipocket-20.08.1.tar.xz : 9974c36d90fc23d9a3a7172cf1526dc3671bf90f01f608effe92f64fce53c372
homepage   : https://kde.org/applications/graphics/org.kde.kdegraphics-mobipocket
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
