name       : kdegraphics-mobipocket
version    : 19.04.1
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/kdegraphics-mobipocket-19.04.1.tar.xz : 345be42b0fb4f2040ce1430c872c0d20b0abaa266159a19beac1b067b2723821
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
