name       : kdegraphics-mobipocket
version    : 22.04.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/kdegraphics-mobipocket-22.04.0.tar.xz : 33640fcef6d379f1dbfe9bc6ccedeba9b744c3c75f8f929f24795a511c5d364a
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - extra-cmake-modules
    - pkgconfig(Qt5Core)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
