name       : kdegraphics-mobipocket
version    : 21.12.0
release    : 57
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/kdegraphics-mobipocket-21.12.0.tar.xz : c2a31b030024b000772ef2d913afe8b6e4829594b56c081e65ea415c21952c13
homepage   : https://apps.kde.org/kdegraphics_mobipocket/
license    : GPL-2.0-or-later
component  : programming
summary    : Plugins for mobpocket
description: |
    A collection of plugins to handle mobipocket files.
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
